version: '3.8'

services:
  geth:
    build:
      context: .
    command: >
      bash -c "./geth init --datadir=/data ./sepolia/genesis.json &&
      ./geth
      --datadir=/data
      --networkid=51515151
      --rollup.sequcerhttp="{$SEQUENCER_HTTP}"
      --syncmode=snap
      --gcmode=full
      --port={$PORT_GETH_P2P:-39393}
      --dispovery.port={$PORT_GETH_P2P:-39393}
      --maxpeers=0
      --http
      --http.vhosts="*"
      --http.corsdomain="*"
      --http.addr=0.0.0.0
      --http.api=web3,debug,eth,txpool,net,engine
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins=*
      --ws.api=debug,eth,txpool,net,engine
      --authrpc.vhosts="*"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.jwtsecret=/data/jwt.txt
      --rollup.disabletxpoolgossip=true"
    ports:
      - 8545:8545 # http
      - 8546:8546 # ws
    volumes:
      - ./${DATA_DIR}:/data
    networks:
      - op-network
    env_file:
      - .env

  node:
    build:
      context: .
    depends_on:
      - geth
    command: >
      bash -c "./op-node
      --l1=${L1_RPC_URL}
      --l1.rpckind=any
      --l1.beacon=${L1_BEACON_URL}
      --l2=http://geth:8551
      --l2.jwt-secret=/data/jwt.txt
      --verifier.l1-confs=4
      --rpc.addr=127.0.0.1
      --rpc.port=9545
      --rollup.config=./sepolia/rollup.json
      --syncmode=execution-layer"
    networks:
      - op-network
    volumes:
      - ./${DATA_DIR}:/data
    ports:
      - 9545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
    env_file:
      - .env

networks:
  op-network:
    driver: bridge