version: '3.8'

services:
  geth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545       # RPC
      - 8546:8546       # websocket
      - 30303:30303     # P2P TCP (currently unused)
      - 30303:30303/udp # P2P UDP (currently unused)
      - 7301:6060       # metrics
    command: [ "bash", "./config/geth-entrypoint" ]
    volumes:
      - ${GETH_HOST_DATA_DIR}:/data
    networks:
      - op
    env_file:
      - ./config/env.sepolia

  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - geth
    networks:
      - op
    ports:
      - 7545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
      - 6060:6060     # pprof
    command: [ "bash", "./config/op-node-entrypoint" ]
    env_file:
      - ./config/env.sepolia

  batcher:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - node
    networks:
      - op
    command: [ "bash", "./config/batcher-entrypoint" ]  
    env_file:
      - ./config/env.sepolia

  proposer:
    build: .
    depends_on:
      - batcher
    networks:
      - op
    command: [ "bash", "./config/proposer-entrypoint" ]  
    env_file:
      - ./config/env.sepolia

networks:
  op:
    driver: bridge