version: '3.8'

services:
  geth:
    build:
      context: .
    command: >
      bash -c "./geth init --datadir=/data ./config/${NETWORK_TYPE}/genesis.json &&
      ./geth
      --datadir=/data
      --networkid=51515151
      --syncmode=full
      --gcmode=archive
      --nodiscover
      --maxpeers=0
      --http
      --http.vhosts="*"
      --http.corsdomain="*"
      --http.addr=0.0.0.0
      --http.api=web3,debug,eth,txpool,net,engine
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins=*
      --ws.api=debug,eth,txpool,net,engine
      --authrpc.vhosts="*"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.jwtsecret=/data/jwt.txt
      --rollup.disabletxpoolgossip=true"
    ports:
      - 8545:8545 # http
      - 8546:8546 # ws
    volumes:
      - ./${DATA_DIR}:/data
    networks:
      - op-network
    env_file:
      - .env

  node:
    build:
      context: .
    depends_on:
      - geth
    command: >
      bash -c "./op-node
      --l1=${L1_RPC_URL}
      --l1.rpckind=any
      --l1.beacon=${L1_BEACON_URL}
      --l2=http://geth:8551
      --l2.jwt-secret=/data/jwt.txt
      --sequencer.enabled
      --sequencer.l1-confs=5
      --verifier.l1-confs=4
      --rollup.config=./config/${NETWORK_TYPE}/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8547
      --rpc.enable-admin
      --p2p.sequencer.key=${SEQUENCER_PRIVATE_KEY}"
    networks:
      - op-network
    volumes:
      - ./${DATA_DIR}:/data
    ports:
      - 9545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
    env_file:
      - .env

  batcher:
    build:
      context: .
    depends_on:
      - node
    command: >
      bash -c "./op-batcher
      --l1-eth-rpc=${L1_RPC_URL}
      --l2-eth-rpc=http://geth:8545
      --rollup-rpc=http://node:8547
      --sub-safety-margin=6
      --poll-interval=1s
      --num-confirmations=1
      --safe-abort-nonce-too-low-count=3
      --resubmission-timeout=30s
      --rpc.addr=0.0.0.0
      --rpc.port=8548
      --rpc.enable-admin
      --max-channel-duration=1
      --private-key=${BATCHER_PRIVATE_KEY}"
    ports:
      - "6061:6060"
      - "7301:7300"
      - "6545:8545"
    networks:
      - op-network
    env_file:
      - .env.sepolia

  proposer:
    build: .
    depends_on:
      - batcher
    command: >
      bash -c "./op-proposer
      --l1-eth-rpc=${L1_RPC_URL}
      --rollup-rpc=http://node:8547
      --poll-interval=12s
      --rpc.port=8560
      --l2oo-address=${L2OO_ADDRESS}
      --private-key=${PROPOSER_PRIVATE_KEY}"
    networks:
      - op-network
    env_file:
      - .env.sepolia

networks:
  op-network:
    driver: bridge