version: '3.8'

services:
  geth:
    build:
      context: .
    command: [ "bash", "./entrypoint-geth" ]
    ports:
      - 8545:8545 # http
      - 8546:8546 # ws
    volumes:
      - ./${DATA_DIR}:/data
    networks:
      - op-network
    env_file:
      - ../.env

  node:
    build:
      context: .
    depends_on:
      - geth
    command: [ "bash", "./entrypoint-op-node" ]
    networks:
      - op-network
    volumes:
      - ./${DATA_DIR}:/data
    ports:
      - 9545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
    env_file:
      - ../.env

  batcher:
    build:
      context: .
    depends_on:
      - node
    command: [ "bash", "./entrypoint-batcher" ]
    networks:
      - op-network
    env_file:
      - ../.env

  proposer:
    build: .
    depends_on:
      - batcher
    command: [ "bash", "./entrypoint-proposer" ]
    networks:
      - op-network
    env_file:
      - ../.env

networks:
  op-network:
    driver: bridge