version: '3.8'
services:
  init:
    build:
      context: .
    image: dreamcacao/optimism_builder_run:0.0.1
    command: [ "bash", "/script/init-entrypoint.sh" ]
    volumes:
      - ${GETH_DATA_DIR}:/data
      - ${CONFIG_DIR}:/config
    env_file:
      - .env
  geth:
    image: dreamcacao/optimism_builder_run:0.0.1
    depends_on:
      init:
        condition: service_completed_successfully
    command: [ "bash", "/script/geth-entrypoint.sh" ]
    ports:
      - 8545:8545 # http
      - 8546:8546 # ws
      - 8551:8551 # auth http
    volumes:
      - ${GETH_DATA_DIR}:/data
      - ${CONFIG_DIR}:/config
    networks:
      - op-network
    env_file:
      - .env
  node:
    image: dreamcacao/optimism_builder_run:0.0.1
    depends_on:
      - geth
    command: [ "bash", "/script/op-node-entrypoint.sh" ]
    networks:
      - op-network
    volumes:
      - ${GETH_DATA_DIR}:/data
      - ${CONFIG_DIR}:/config
    ports:
      - 8547:8547 # RPC
    env_file:
      - .env
  batcher:
    image: dreamcacao/optimism_builder_run:0.0.1
    depends_on:
      - node
    command: [ "bash", "/script/op-batcher-entrypoint.sh" ]
    networks:
      - op-network
    env_file:
      - .env
  proposer:
    image: dreamcacao/optimism_builder_run:0.0.1
    depends_on:
      - batcher
    command: [ "bash", "/script/op-proposer-entrypoint.sh" ]
    networks:
      - op-network
    env_file:
      - .env
networks:
  op-network:
    driver: bridge