version: '3.8'
services:
  init:
    build:
      context: .
    image: run_init
    command: [ "bash", "/app/entrypoint-init" ]
    volumes:
      - ${GETH_DATA_DIR}:/data
    env_file:
      - .env
  geth:
    build:
      context: .
    image: run_geth
    depends_on:
      init:
        condition: service_completed_successfully
    command: [ "bash", "/app/entrypoint-geth" ]
    ports:
      - 8545:8545 # http
      - 8546:8546 # ws
      - 8551:8551 # auth http
    volumes:
      - ${GETH_DATA_DIR}:/data
    networks:
      - op-network
    env_file:
      - .env

  node:
    build:
      context: .
    image: run_op_node
    depends_on:
      - geth
    command: [ "bash", "/app/entrypoint-op-node" ]
    networks:
      - op-network
    volumes:
      - ${GETH_DATA_DIR}:/data
    ports:
      - 8547:8547     # RPC
    env_file:
      - .env

  batcher:
    build:
      context: .
    image: run_op_batcher
    depends_on:
      - node
    command: [ "bash", "/app/entrypoint-op-batcher" ]
    networks:
      - op-network
    env_file:
      - .env

  proposer:
    build:
      context: .
    image: run_op_proposer
    depends_on:
      - batcher
    command: [ "bash", "/app/entrypoint-op-proposer" ]
    networks:
      - op-network
    env_file:
      - .env

networks:
  op-network:
    driver: bridge